import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import styles from "../styles/Home.module.css";

import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
	return {
		props: { coffeeStores: coffeeStoresData },
	};
}

export default function Home(props) {
	console.log("props", props);
	const handleOnBannerBtnnClick = () => {
		console.log("hey button");
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Connoisseur </title>
				{/* <title>{query} </title> */}
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				{/* <footer className={styles.footer}></footer> */}
				<Banner
					buttonText="View stores nearby"
					handleOnClick={handleOnBannerBtnnClick}
				/>
				<div className={styles.heroImage}>
					<Image src="/static/hero-image.png" width={700} height={400} />
				</div>
				{props.coffeeStores.length > 0 && (
					<>
						<h2 className={styles.heading2}>Toronto stores </h2>
						<div className={styles.cardLayout}>
							{props.coffeeStores.map((coffeeStore) => {
								return (
									<Card
										key={coffeeStore.id}
										name={coffeeStore.name}
										imgUrl={coffeeStore.imgUrl}
										href={`/coffee-store/${coffeeStore.id}`}
										neighbourhood={coffeeStore.neighbourhood}
										address={coffeeStore.address}
										className={styles.card}
									/>
								);
							})}
						</div>
					</>
				)}
			</main>
		</div>
	);
}
